Numpy - Numerical Python

1.   Used for various mathematical operations (matrix, array etc)
2.   Faster operations




Importing Numpy

In [ ]:
import numpy as np

Numpy Array vs List

In [ ]:
list_test = [1,2,3,4,5]
print(list_test)
type(list_test)

[1, 2, 3, 4, 5]


list

In [ ]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

Creating a 1-dimensional array

In [ ]:
a = np.array([1,2,3,4])
print(a)
#prints the size of array (row, col)
print(a.shape)

[1 2 3 4]
(4,)


Creating a 2-dimensional array

In [ ]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]
 [5 6 7 8]]
(5, 4)


Floating point values in Array

In [ ]:
#dtype used to specify the datatype
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Array Sort

In [ ]:
arr = np.array([3, 2, 0, 1])
#ascending
print(np.sort(arr))
#descending
print(np.sort(arr)[::-1])



[0 1 2 3]
[3 2 1 0]


Numpy Random

In [ ]:
#prints a random number
from numpy import random

x = random.randint(100)
print(x)


#float (0 to 1)
x = random.rand()
print(x)


32
0.4199738097524105
